module.exports = [
    {
        name: "Graphic Sweatshirt",
        description:
            "Bold graphic sweatshirt with a soft fleece lining. Great for chilly days and layering.",
        brand: "JumpStart",
        material: "Fleece",
        size: ["XS", "S", "M", "L"],
        color: "Orange",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/61t88tX8rnL.jpg",
        isFeatured: true,
    },
    {
        name: "Rainbow Hoodie",
        description:
            "A cozy hoodie with a bright rainbow print and soft lining. Keeps kids warm while looking cool.",
        brand: "PlayPatch",
        material: "Cotton",
        size: ["XS", "S", "M", "L"],
        color: "Yellow",
        price: 1395,
        category: "KIDS",
        image: "https://images-cdn.ubuy.co.in/63d5365d86bf80118b5097a1-adarl-kids-girl-rainbow-hoodies-jacket.jpg",
    },
    {
        name: "Graphic Tee",
        description:
            "Trendy graphic t-shirt with bold prints. Crafted from soft cotton for all-day comfort and a statement look, suitable for streetwear lovers.",
        brand: "ExecutiveLine",
        material: "Wool",
        size: ["S", "M", "L", "XL"],
        color: "Yellow",
        price: 449,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRJGXBdUQLKcZMmN2F-qF0-xKQIwcWhWgk9f4pEp2eHAtLNZrqWlLqE0bKGJoblna2eiwkMyr7MVbrGgYeHewfk050vxtkzmtevpcHIy58X",
        isFeatured: true,
    },
    {
        name: "Active Zip Jacket",
        description:
            "Sporty zip-up jacket with breathable panels. Great for cool mornings.",
        brand: "BunnyBop",
        material: "Spandex",
        size: ["XS", "S", "M", "L"],
        color: "Gray",
        price: 1299,
        category: "KIDS",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRKPSBJGieOyA3ywvPh-eMtG0isiEN4h0MY3aC0pUAKJKvFsiki3ZtX0rVn1_zROC5qfRM_FJsEmCL-Ow8_mo5XlA6r1FS7mmOAThcD09k9_01-v58IMwnJhAc",
    },
    {
        name: "Soft Knit Cardigan",
        description:
            "Lightweight knit cardigan with button closure. Ideal for layering in all seasons.",
        brand: "BunnyBop",
        material: "Denim",
        size: ["S", "M", "L"],
        color: "Mint",
        price: 699,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/716XHXDf5pL._UF894,1000_QL80_.jpg",
    },
    {
        name: "Skater Skirt",
        description:
            "A stylish skater skirt with fun prints and stretch waistband. Great for twirls and fun.",
        brand: "LivelyLoom",
        material: "Rayon",
        size: ["XS", "S", "M"],
        color: "Pink",
        price: 1395,
        category: "KIDS",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSjtoOnSBTCW-z4hs5G1UAOPqku0az-d9jjFyG73UnymM4l0z7llNNbT980FmHnBIT6do4U7MuJZbOyszwlEI0t-RstA_XEQxWc_onRyKyndf0DxwKDbMeaWw",
    },
    {
        name: "Unicorn Nightdress",
        description:
            "Whimsical nightdress with unicorn graphics and glitter details. Comfy and magical!",
        brand: "LittleLoop",
        material: "Canvas",
        size: ["XS", "S", "M"],
        color: "Mint",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/717cnvTX-rL._AC_UY1100_.jpg",
    },
    {
        name: "Performance Zip Track Jacket",
        description:
            "Sporty zip-up track jacket built for movement and breathability. Lightweight yet protective — great for gym warmups or outdoor activities.",
        brand: "FitZone",
        material: "Cotton",
        size: ["M", "L", "XL"],
        color: "Brown",
        price: 549,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQq-XdBVQ0YKQxCj8p669IbBJqIzvCtFmi11ss7WDswW26rIv7m5pVXT9qns65t6hoo8hrA7GJq0mJSSTyscI2nzoaB30ryUOdROpD2w_TdxX1HplSqE8Fz0A",
    },
    {
        name: "Thermal Base Set",
        description:
            "Thermal top and bottom set for winter warmth. Ideal for layering under clothes.",
        brand: "RainbowHug",
        material: "Fleece",
        size: ["S", "M", "L"],
        color: "Green",
        price: 1349,
        category: "KIDS",
        image: "https://i.etsystatic.com/19801087/r/il/40c07e/6265230810/il_570xN.6265230810_jvm4.jpg",
        isFeatured: true,
    },
    {
        name: "Tapered Fit Pants",
        description: "Ankle-length tapered pants for sleek office looks.",
        brand: "LuxeCharm",
        material: "Nylon",
        size: ["S", "M", "L", "XL"],
        color: "Lilac",
        price: 1395,
        category: "WOMEN",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlGS6Fbj0TS7iSNadHEGtBTbf6W0O0agxoyFCnE4N8ZPc6Bd9pq5frCXhTIYURVtCph8H9DZebhN31q6c1xHwfyT97TYEANnzGHOf-clJYWOVuAw1axc55wQ",
        isFeatured: true,
    },
    {
        name: "DryFit Training Shorts",
        description:
            "Lightweight and moisture-wicking training shorts designed for high-intensity workouts. Includes side mesh panels for better ventilation.",
        brand: "ActiveTrend",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "Red",
        price: 1249,
        category: "MEN",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFJLQTa6EsD5HWPJkelpWJ8xgn6_9fgkYlhJyxiBiUhOI0j2_9DaS2doBer5xT_kOJbRfUXhaaapQrwAmVXZRfH7hcs3HPI_crcb9zM8J6pA-66q9JdYrmHg",
    },
    {
        name: "Tie-Dye Tee",
        description:
            "Trendy tie-dye t-shirt that kids love. Every piece has a unique swirl of colors.",
        brand: "MerryMob",
        material: "Spandex",
        size: ["XS", "S", "M", "L"],
        color: "Gray",
        price: 499,
        category: "KIDS",
        image: "https://i.etsystatic.com/47036642/r/il/9b2f41/5333271912/il_570xN.5333271912_3p8d.jpg",
    },
    {
        name: "Soft Shorts 2-Pack",
        description:
            "Set of two soft shorts in playful prints. Ideal for playtime and summer fun.",
        brand: "GiggleWear",
        material: "Jersey",
        size: ["XS", "S", "M", "L"],
        color: "Purple",
        price: 799,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTspmTW3TGuRgDWSoFEnhz8mL1VLVDsHVDfOQ&s",
    },
    {
        name: "Printed Shorts",
        description:
            "Comfy shorts with elastic waistband and bold prints. Perfect for everyday wear.",
        brand: "DinoDen",
        material: "Denim",
        size: ["XS", "S", "M", "L"],
        color: "Maroon",
        price: 1395,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/51E13dF47jL.jpg",
    },
    {
        name: "Belted Shirt Dress",
        description:
            "Classic shirt dress with a detachable belt and button-down front. Stylish and professional.",
        brand: "GlowThread",
        material: "Georgette",
        size: ["S", "M", "L", "XL"],
        color: "Rose",
        price: 1249,
        category: "WOMEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSnR9Q_aQAdh87H76jq5nyOZykRATwS13kc-Of1nDJtHGSaPM61EZgxyVWelu3W1LAWanYd4e7Fz0Lb8RM6YYc0apxgDyZLwHEzDCwiOws",
    },
    {
        name: "Paperbag Waist Shorts",
        description:
            "High-rise shorts with a paperbag waist and belt. A stylish pick for warmer seasons.",
        brand: "SheNova",
        material: "Lace",
        size: ["S", "M", "L"],
        color: "Peach",
        price: 1499,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREiRkG7LtdfCT-GG8nxzke_XRjk7vDiF_h9g&s",
    },
    {
        name: "Halter Neck Top",
        description: "Sleek halter top suitable for parties or night outs.",
        brand: "BloomEra",
        material: "Wool",
        size: ["XS", "S", "M"],
        color: "White",
        price: 649,
        category: "WOMEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS1YdDhwKaURupsHrwU69IFtIuj7Gw93MqUi6M4bptfokegFQn3lIOiYdRneQS9iq-bX2UsNN2EeNox23LpLv2eDjf_JMiEg4kjXKrfZfU",
        isFeatured: true,
    },
    {
        name: "Lightweight Crewneck Sweatshirt",
        description:
            "A minimalistic crewneck sweatshirt made from soft, breathable fabric. Perfect for layering or wearing solo in cooler seasons.",
        brand: "BreezeFit",
        material: "Polyester",
        size: ["S", "M", "L", "XL"],
        color: "Olive",
        price: 1449,
        category: "MEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSWMZ04qa0YL9ChlFzWn5Bvvsk8JoN0L12jvCg1GgECwyviHJ3kw7AoDaeCZ-jIAEPtuCpsJes3HGHUUkXTHeKjJ8Zgosi-V4bMutE_hdnR",
    },
    {
        name: "Stars and Stripes Pajamas",
        description:
            "Fun two-piece pajamas with patriotic prints. Made for cozy and cool nights.",
        brand: "GiggleWear",
        material: "Chambray",
        size: ["S", "M", "L"],
        color: "Sky Blue",
        price: 649,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/81ixK6FVKfL._UY1000_.jpg",
    },
    {
        name: "Basic Tank Top",
        description:
            "A breathable cotton tank top suited for layering or lounging. Simple, comfy, and versatile.",
        brand: "BloomEra",
        material: "Satin",
        size: ["XS", "S", "M", "L"],
        color: "Sky Blue",
        price: 699,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/61jxrXCSxZL.jpg",
    },
    {
        name: "Lace Blouse",
        description:
            "Delicate lace blouse with semi-sheer sleeves and intricate embroidery. Adds charm to any formal or festive look.",
        brand: "UrbanBelle",
        material: "Wool",
        size: ["S", "M", "L"],
        color: "Beige",
        price: 949,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/431110760/csvdi_1200.jpg",
    },
    {
        name: "Tank Top",
        description:
            "Simple and breathable tank top for gym sessions or summer wear. Provides ease of movement and keeps you cool during intense workouts.",
        brand: "ExecutiveLine",
        material: "Denim",
        size: ["S", "M", "L"],
        color: "Blue",
        price: 449,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSa4DDf0ZPkv13Cn64f2TvnGV9B9mfzGrDCeWuBJRQdHivqMfgAGKIxBSJV0jlMyC_lwEY0anntjdMIb_R8MN37dTFLDhq73YdXF-qsQn23n7Kw-vFZzYH9",
    },
    {
        name: "Balloon Sleeve Kurti",
        description:
            "Fusion kurti with trendy balloon sleeves and cotton comfort.",
        brand: "LuxeCharm",
        material: "Satin",
        size: ["M", "L", "XL", "XXL"],
        color: "Pink",
        price: 449,
        category: "WOMEN",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSt1J07Haodg2cLEm1o7P5VL1WvsoU8FjS68wOzPAJIo0TUWdBkJCTXAkAis4bSxt97Vj-Nvupql1oq5up9TQp57lTlYgrQ9EGNgkA_bF1byFe8iGnD17Lh",
    },
    {
        name: "Cartoon Print T-Shirt",
        description:
            "A fun and colorful t-shirt featuring popular cartoon characters. Made for everyday play and comfort.",
        brand: "RainbowHug",
        material: "Terry",
        size: ["XS", "S", "M", "L"],
        color: "Maroon",
        price: 1249,
        category: "KIDS",
        image: "https://images.meesho.com/images/products/447755320/hrvhq_1200.jpg",
    },
    {
        name: "Reversible Bomber Jacket",
        description:
            "Trendy bomber jacket with two different looks. Zips up and keeps warm.",
        brand: "RainbowHug",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Yellow",
        price: 699,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpBnYcI3rI0GP-Z9VXUGG-xiFwZPk_umZXoxjSS2xVplUAV7_GGQU146LNbqNNg2Bq2kw&usqp=CAU",
    },
    {
        name: "Denim Dungarees",
        description:
            "Classic denim dungarees with adjustable straps and roomy pockets. Perfect for playdates and outings.",
        brand: "CozyCritters",
        material: "Spandex",
        size: ["S", "M", "L"],
        color: "Green",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/71f5UkDNLlL.jpg",
    },
    {
        name: "Minimalist Sleeveless Top",
        description:
            "A clean, minimalist sleeveless tee for gym sessions or summer heat. Lightweight and non-restrictive for complete freedom of movement.",
        brand: "ExecutiveLine",
        material: "Suede",
        size: ["S", "M", "L"],
        color: "Green",
        price: 1399,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSoH1D5IZ3-NC6gl-mN4u5vgJ13RWGSCwkh7g87OkbszRNxblewV_L511uaD4Hv9oK6JHg6H_pr9x5KlxRw57xJp4INuhQUObdm4KLRhWSZDGvJkZIblL7W",
    },
    {
        name: "Comfy Lounge Set",
        description:
            "Matching set with a long-sleeve tee and joggers. Cozy for relaxing at home.",
        brand: "PuddlePals",
        material: "Fleece",
        size: ["S", "M", "L"],
        color: "Yellow",
        price: 649,
        category: "KIDS",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTpxvCUQS076UXLDQJ3589m8IM5XR9fbL7MVXPo1tg9JUcpPKnu0HA1TqKO2cByEC68VYNnsrE-Arg05GXC5Y9ut6Rei0XMt9xd-nKvt6FFJr6nFD5QXEJHJA",
    },
    {
        name: "Printed Kurti",
        description:
            "Traditional yet trendy printed kurti perfect for fusion wear or ethnic days.",
        brand: "LilyLine",
        material: "Polyester",
        size: ["M", "L", "XL", "XXL"],
        color: "Black",
        price: 549,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/71MVKV3MRJL.jpg",
    },
    {
        name: "Lightweight Jacket",
        description:
            "Water-resistant lightweight jacket suitable for spring and fall. Features zip-up front, elastic cuffs, and breathable mesh lining inside.",
        brand: "CoreStyle",
        material: "Wool",
        size: ["S", "M", "L"],
        color: "Purple",
        price: 899,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRKByjZAjQtI5je8k7uVqxa_WC0O1GmpjyO9iOy0WcM25bOVZX10_E5m6zSn0Bc_SzBy0p8p_fZg38neUf2-gMrEZ8EPbB5wMBJy4UQLEJGCFFvM-XtyBeD",
    },
    {
        name: "Full Sleeve Hoodie",
        description:
            "Premium full-sleeve hoodie with brushed fleece lining for added warmth. Designed with a front zipper and a relaxed fit for maximum comfort.",
        brand: "UrbanEdge",
        material: "Suede",
        size: ["M", "L", "XL", "XXL"],
        color: "Pink",
        price: 1099,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQMqZhgrHrJ6OQDbsyjSD5tZUcAVPAgRE6ERTXSLaUOzZRTI9lg-x-3Esz_8E1Lg2qFPbG0ZjI3yWxgJfvNTSWoK_C4nRkYVzjgowz9RkYGBXSYpOlIKDLutg",
        isFeatured: true,
    },
    {
        name: "Sleeveless Workout Tee",
        description:
            "This muscle-cut tank is great for gym training and active movement. Lightweight and moisture-wicking to keep you cool during workouts.",
        brand: "StreetPulse",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "Teal",
        price: 1249,
        category: "MEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcShtHC7pZdCOvHFwR0Bm9io4l2ZIYGsQ2Ud5VFICreoSchdrmh8ytH0gALDAuqkP7x2Iipbo8zxEiajpCGOTfU8Zq7P9qFLLSu45rtckemyM6iGl5JYPczu",
    },
    {
        name: "Loose Fit Training Tee",
        description:
            "Performance training tee with a loose, breathable fit. Designed to keep you cool and dry during workouts or intense physical activity.",
        brand: "LayerUp",
        material: "Rayon",
        size: ["S", "M", "L"],
        color: "Blue",
        price: 899,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQegCEs7vHsd_i3X2Y2CfnsWP6d1tTTtOMguc06K0R6euxRitEEDX4K5usSWRnD14bPCvlxguH0NnSMxWkSXSlPgdgIzIK2hZe2RVHlDvbMhAXjH0Jz4knooNk",
    },
    {
        name: "Workout Compression Tee",
        description:
            "Performance tee with light compression, ideal for training sessions. Quick-drying and breathable fabric supports movement and keeps you cool.",
        brand: "FitZone",
        material: "Fleece",
        size: ["S", "M", "L", "XL"],
        color: "Teal",
        price: 499,
        category: "MEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRTl1d47ZTDa1z3sxVYz21l_B0YEsLUcGnAGNNt1TuMqfKtc_zNxoLnk7hOBRepl3UwSjjHthfgXljehm9Zn6BUdtAE0lNbw9W3GxGI0Bw4uA4m4cFeF5jF",
        isFeatured: true,
    },
    {
        name: "Wide-Leg Palazzo Pants",
        description:
            "Comfortable and flowy palazzo pants for both casual and semi-formal wear.",
        brand: "Eleganza",
        material: "Wool",
        size: ["M", "L", "XL"],
        color: "Lilac",
        price: 1299,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/550056009/fl3be_1200.jpg",
    },
    {
        name: "Ankle-Length Jeggings",
        description:
            "Super stretchable jeggings for comfort and versatility. Pairs well with tunics or tees.",
        brand: "SoftHue",
        material: "Denim",
        size: ["XS", "S", "M", "L"],
        color: "Charcoal",
        price: 1199,
        category: "WOMEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTctOx6vN5RAVNzZdip_omnejCOiwaOYFVEt4OXmUVh_bxpcun6EYdpEXFETV5RnKd71VGYIedMA75tuUowkdhsNbHsIN-baGgdvQbDDpU8Qr-3i2HjABhO",
    },
    {
        name: "High-Waist Leggings",
        description:
            "Stretchable high-rise leggings perfect for yoga, gym, or relaxed wear. Provides both support and comfort.",
        brand: "SheNova",
        material: "Rayon",
        size: ["XS", "S", "M", "L"],
        color: "Beige",
        price: 1299,
        category: "WOMEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQXCJQ8sJpWuNv5gJPZt96-a-PwVG2nkW7UGC__snm20JhpfRwUZ5ZIN5BJMqiVmoqIAaWfU7oUVvaxoTpvki2AUqDEN5hI4mEtuFUGjmjyRR6w_ohoRtQXzg",
    },
    {
        name: "Printed Round Neck Tee",
        description:
            "Bold printed tee with a unique front design. Crafted from soft cotton fabric and suitable for casual everyday outfits or weekend hangouts.",
        brand: "StreetPulse",
        material: "Leather",
        size: ["S", "M", "L", "XL"],
        color: "Navy",
        price: 649,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRp4iVZPgZX6NFGWwaRDMFeD5fY0xTKYAjqaveTZCkwN6kgw3kzXJ_Apz0V2mNUREAFjlKUs7vRjUXwcmpHai8Jg2nVed1tnnKRat0z0IaeCg9U3Q2YPc7z",
    },
    {
        name: "Formal Dress Shirt",
        description:
            "Classic long-sleeve dress shirt with a sharp collar and buttoned cuffs. Great for office wear or formal occasions with a suit and tie.",
        brand: "EveryWear",
        material: "Spandex",
        size: ["M", "L", "XL"],
        color: "Brown",
        price: 1395,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTN807ZUTVWEXEUi_tYvBVrvRoQ5D7GJLf7T-_yv34HwLxLSG0lOkTO6ZMH2LlwMNr4amsVTBAgVWAgReWNqp2gf6wxElOwltIZ_DcUHHI",
    },
    {
        name: "Ruffle Shoulder Top",
        description:
            "Girly top with ruffle shoulders and bright patterns. Perfect for casual days.",
        brand: "MiniMode",
        material: "Chambray",
        size: ["XS", "S", "M"],
        color: "Turquoise",
        price: 1099,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/91vMaDIKHAL._AC_UY1100_.jpg",
    },
    {
        name: "Polka Dot Skirt",
        description:
            "A twirly polka dot skirt with an elastic waistband. Pairs well with tees and cardigans.",
        brand: "MiniMode",
        material: "Fleece",
        size: ["XS", "S", "M"],
        color: "Gray",
        price: 599,
        category: "KIDS",
        image: "https://images.meesho.com/images/products/141233966/p4cdf_512.webp",
    },
    {
        name: "Shirred Smock Dress",
        description:
            "Smock dress with a shirred bodice and puff sleeves. Soft and flowy.",
        brand: "Eleganza",
        material: "Polyester",
        size: ["S", "M", "L"],
        color: "Lilac",
        price: 949,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/428082937/tw1wa_1200.jpg",
    },
    {
        name: "Zip Neck Sweatshirt",
        description:
            "Half-zip sweatshirt made from warm cotton blend fabric. Great for layering during colder seasons, with a modern athletic cut.",
        brand: "DenimWorks",
        material: "Linen",
        size: ["M", "L", "XL"],
        color: "Yellow",
        price: 1450,
        category: "MEN",
        image: "https://images.meesho.com/images/products/456861046/ifmkx_512.webp",
        isFeatured: true,
    },
    {
        name: "Princess Tutu Dress",
        description:
            "A sparkly tutu dress for little royalty. Great for parties, play, or dress-up.",
        brand: "PuddlePals",
        material: "Velour",
        size: ["XS", "S", "M"],
        color: "Orange",
        price: 1450,
        category: "KIDS",
        image: "https://i.etsystatic.com/14572646/r/il/c3dbbd/3156089859/il_fullxfull.3156089859_infp.jpg",
        isFeatured: true,
    },
    {
        name: "Jogger Set",
        description:
            "Matching jogger set with hoodie and pants. Soft and durable for play or lounge time.",
        brand: "CubCove",
        material: "Acrylic",
        size: ["S", "M", "L"],
        color: "Green",
        price: 799,
        category: "KIDS",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSPzcTAWQHLU6BORYAbFNaCdUcVBxyv7SmC5b0mjd3S0jvMlj9hy6w2D1kHr0QRgEtsqs7w87hm3ykaL9ES9wogXzJdTnd83XAlv6sC1JqElZVocMMC2QSy",
    },
    {
        name: "Velvet Party Dress",
        description:
            "Plush velvet dress with rich tones. Ideal for evening occasions.",
        brand: "SoftHue",
        material: "Acrylic",
        size: ["S", "M", "L"],
        color: "White",
        price: 1450,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/51vhPSKJUYL.jpg",
    },
    {
        name: "Sleeveless Blazer",
        description:
            "A modern twist on the blazer with sleeveless cut. Professional yet stylish.",
        brand: "SerenityWear",
        material: "Satin",
        size: ["S", "M", "L"],
        color: "Coral",
        price: 499,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4iO12_Cifwmfk5FsNNZggB7YMfp2jtYJ-Cg&s",
    },
    {
        name: "Textured Lounge Set",
        description:
            "2-piece lounge set with a comfy textured fabric, great for home or errands.",
        brand: "GraceNote",
        material: "Linen",
        size: ["M", "L", "XL"],
        color: "Navy",
        price: 549,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ1Mrfo_BoTXdGPW-J_HjdJKdnxbGpno6-iW_5AWXLJrS7TTFvjLnG8Ku9_cSRB3B1QNhL_OUgUZJrkfoos5pI-iFDWPlfCEOD8sluj8Ja_iyC_wih56CRPRw",
        isFeatured: true,
    },
    {
        name: "Short Dungarees",
        description:
            "Casual short dungarees for summer play. Features cute front pocket and soft fabric.",
        brand: "WhizKid",
        material: "Jersey",
        size: ["S", "M", "L"],
        color: "Blue",
        price: 1450,
        category: "KIDS",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcScqx9Rl_MGRoUVAz1cJ-S0oXXgSIGckOFSvFp-arFjOSO42zxuO_W_SPzCyxLctlERBqlGOBaJS4uYvGq8jTZtYHKxvz2xH0sXCbWz_jLlHsUnWJ1vEACRXg",
    },
    {
        name: "Fleece Hoodie",
        description:
            "Ultra-soft fleece hoodie for extra warmth. Great for school or home days.",
        brand: "PeekabooWear",
        material: "Tulle",
        size: ["S", "M", "L"],
        color: "Blue",
        price: 749,
        category: "KIDS",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTDC6qgyrjZMkXxFGQOscc9MgDzUr_7Ba7zQcra5UknAvJkJxqCyfayWjnCMH3SsHyt2Gvx4X4rJp58LvQZxV_4LvLnFgsKr3bgKnlT_Kwv1P_eJGh02eBRFqE",
    },
    {
        name: "Knitted Cardigan",
        description:
            "Open-front knitted cardigan that adds warmth and style to any outfit.",
        brand: "VivaModa",
        material: "Georgette",
        size: ["M", "L", "XL"],
        color: "Teal",
        price: 1450,
        category: "WOMEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSXMQ1K7PT_dtR6RGVib-Z8mEWYUZdMT8TMfN68ovW_0CjTRKgsQizKaaRS1kZHiVtQ0zAXCKbwieSfE3EML_eBJ-ebUAdmTgW5v5fLW08",
    },
    {
        name: "Playground Romper",
        description:
            "Easy one-piece romper designed for active play. Soft fabric and cheerful colors.",
        brand: "LittleLoop",
        material: "Canvas",
        size: ["S", "M", "L"],
        color: "Yellow",
        price: 699,
        category: "KIDS",
        image: "https://i5.walmartimages.com/seo/TUOBARR-Girls-Children-s-Summer-Solid-Color-Romper-Sling-Sleeveless-Backless-Short-Jumpsuit-Yellow-1-5Years_bfc8c6d7-ce20-401c-8c56-2ecb56882c77.65375699e192b569f1f68821916ff8e5.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF&odnDynImageQuality=10&format=avif",
    },
    {
        name: "Printed Leggings",
        description:
            "Stretchy leggings with bright and fun prints. Perfect for school or weekend fun.",
        brand: "PuddlePals",
        material: "Denim",
        size: ["S", "M", "L"],
        color: "Teal",
        price: 1199,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/91R69Fa35RL.jpg",
    },
    {
        name: "Crop Hoodie",
        description:
            "Cropped hoodie with a relaxed fit and soft lining. Combines sporty and stylish vibes.",
        brand: "FlairEdge",
        material: "Denim",
        size: ["S", "M", "L", "XL"],
        color: "Sky Blue",
        price: 1450,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/143299286/j5xej_1200.jpg",
    },
    {
        name: "Cargo Joggers",
        description:
            "Durable joggers with multiple pockets and a modern tapered fit. Designed for both utility and style with adjustable drawstring waist.",
        brand: "BaseLayer",
        material: "Polyester",
        size: ["M", "L", "XL", "XXL"],
        color: "Pink",
        price: 1299,
        category: "MEN",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTQf0IPj85KKQdOSoEY0icBM3GA_6M5BNjefMHeXzaqsUL22PSkzlxpNtkQgGU6nUUU3YfpDVV7-BokwT2GPaUg4QWwSHPfUyrJ1r-RQ4Y",
        isFeatured: true,
    },
    {
        name: "Graphic Oversized Tee",
        description:
            "Oversized fit t-shirt with a bold urban graphic. Made from soft-touch cotton, this relaxed style is perfect for streetwear looks.",
        brand: "MuscleFlex",
        material: "Nylon",
        size: ["M", "L", "XL", "XXL"],
        color: "Navy",
        price: 499,
        category: "MEN",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRhOJhPae-xLKgdjE-uYVLoOBJlEHicWmZePAqqNIaoFfVeeG3moQe2tkZOrppotOW7oAPm3m5d-651JFPPP_yep8KBPN2TYrbxbeL0ixQjPjdUhC9TU2ojww",
    },
    {
        name: "Lace Trim Dress",
        description:
            "Delicate dress with lace trim and floral embroidery. Perfect for festive occasions.",
        brand: "RainbowHug",
        material: "Acrylic",
        size: ["XS", "S", "M"],
        color: "Green",
        price: 1199,
        category: "KIDS",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSuMAZ7d6BEWfpA90DnnKBM162q_1Feu0TtH7ylf3jkOCLDvnlS_yWU9lxz1N1im-F0qzgf04Pa_Ha4QF0qdwotovrh2IDtr5d4zjpOWhC1GNxm9pYgKCisFQ",
    },
    {
        name: "Colorblock Joggers",
        description:
            "Trendy joggers with colorblock panels and soft interior lining. Ideal for active kids.",
        brand: "PlayPatch",
        material: "Spandex",
        size: ["XS", "S", "M", "L"],
        color: "Lavender",
        price: 1449,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/51OzNCA7MTL.jpg",
    },
    {
        name: "Kaftan Top",
        description:
            "Loose and breezy kaftan top ideal for hot climates and effortless styling.",
        brand: "VelvaShe",
        material: "Silk",
        size: ["M", "L", "XL"],
        color: "Charcoal",
        price: 799,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/421072182/bcufk_1200.jpg",
    },
    {
        name: "Relaxed Fit Lounge Pants",
        description:
            "Lounge comfortably in these relaxed-fit cotton pants. Elastic waistband and soft touch fabric make them perfect for home or casual days out.",
        brand: "RusticMode",
        material: "Spandex",
        size: ["M", "L", "XL", "XXL"],
        color: "Brown",
        price: 1450,
        category: "MEN",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQEJqNtpdziKqDF3Hdd0ziD68hqy6ZAMEPC5vgTCorxG2Kvg9Fl-1wS2q3U5xvDswXsta_l-Jw8mEDMyqCGK-X8U4r5dNffLeFjP9hisnMY",
    },
    {
        name: "Raincoat with Ears",
        description:
            "Cute raincoat with animal ears on the hood and waterproof lining. Rainy days made fun!",
        brand: "MiniMode",
        material: "Velour",
        size: ["XS", "S", "M"],
        color: "Turquoise",
        price: 599,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/61kcKyG6IrL._UY1100_.jpg",
    },
    {
        name: "Tulle Skirt",
        description:
            "Voluminous tulle skirt perfect for parties or fashion-forward outings.",
        brand: "VivaModa",
        material: "Polyester",
        size: ["S", "M", "L"],
        color: "Cream",
        price: 1449,
        category: "WOMEN",
        image: "https://balticborn.com/cdn/shop/products/mila-tulle-skirt-cream-960964.jpg?v=1741703188",
    },
    {
        name: "Button-Front Skirt",
        description:
            "Stylish A-line skirt with button detailing. Great with fitted tops.",
        brand: "GraceNote",
        material: "Polyester",
        size: ["S", "M", "L"],
        color: "White",
        price: 799,
        category: "WOMEN",
        image: "https://assets.ajio.com/medias/sys_master/root/20210403/C1iy/60690c6daeb269a9e33d7f16/-473Wx593H-462069715-white-MODEL.jpg",
    },
    {
        name: "Sheath Dress",
        description:
            "Tailored sheath dress for an elegant, body-hugging silhouette.",
        brand: "ChicLayer",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "Charcoal",
        price: 1449,
        category: "WOMEN",
        image: "https://www.exude.in/cdn/shop/files/DSC_6278.jpg?v=1749121917&width=1500",
    },
    {
        name: "Plaid Flannel Shirt",
        description:
            "Soft brushed flannel shirt with a classic plaid design. Adds both warmth and style, perfect for layering on cooler days.",
        brand: "StepEase",
        material: "Silk",
        size: ["M", "L", "XL", "XXL"],
        color: "Olive",
        price: 949,
        category: "MEN",
        image: "https://www.gliks.com/cdn/shop/files/001-1897-Legends-Plaid-Flannel-Shirt-for-Men-in-Olive-6PW5643M-OLIVE.jpg?v=1723919335",
    },
    {
        name: "Tiered Maxi Skirt",
        description:
            "Layered maxi skirt with an elastic waistband and boho aesthetic.",
        brand: "AuraVibe",
        material: "Denim",
        size: ["S", "M", "L"],
        color: "Rose",
        price: 1199,
        category: "WOMEN",
        image: "https://assets.sheinindia.in/medias/shein_sys_master/root/20250526/KJsD/6834259d7a6cd4182f4d78ca/-1117Wx1400H-443320985-rose-MODEL.jpg",
    },
    {
        name: "Asymmetric Hem Dress",
        description: "Dress with a playful asymmetric hem for modern flair.",
        brand: "ModernGaze",
        material: "Chiffon",
        size: ["S", "M", "L"],
        color: "Charcoal",
        price: 1299,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIrgrpRi0ME38pFe0TPYp9aocfe-dzcsRy_w&s",
    },
    {
        name: "Colorblock Gym Shorts",
        description:
            "Lightweight gym shorts with a bold colorblock design. Elastic waistband, mesh panels, and breathable fabric make them perfect for training.",
        brand: "RusticMode",
        material: "Denim",
        size: ["S", "M", "L", "XL"],
        color: "Turquoise",
        price: 699,
        category: "MEN",
        image: "https://thumblr.uniid.it/product/247140/f15a9dd1113b.jpg?width=3840&format=webp&q=75",
    },
    {
        name: "Puffer Sleeveless Jacket",
        description:
            "Insulated sleeveless jacket with a quilted design. Great for layering in cold conditions, offering warmth without restricting arm movement.",
        brand: "EveryWear",
        material: "Wool",
        size: ["M", "L", "XL"],
        color: "Gold",
        price: 1450,
        category: "MEN",
        image: "https://5.imimg.com/data5/EQ/DK/CN/SELLER-75155666/puffer-jackets-500x500.jpg",
    },
    {
        name: "Khaki Utility Shirt",
        description:
            "Versatile utility shirt with flap pockets and durable stitching. Ideal for both casual wear and light outdoor activities, with a rugged look.",
        brand: "TrailFlex",
        material: "Linen",
        size: ["M", "L", "XL", "XXL"],
        color: "Olive",
        price: 549,
        category: "MEN",
        image: "https://campussutra.com/cdn/shop/files/CSMSSRT6951_2_d020bdb9-65d5-46c0-8d72-6c5e76a14683.jpg?v=1724336012&width=1080",
    },
    {
        name: "Half Sleeve Linen Shirt",
        description:
            "Breathable half-sleeve shirt made with lightweight linen blend. Perfect for summer outings, keeping you cool and stylish throughout the day.",
        brand: "MuscleFlex",
        material: "Leather",
        size: ["M", "L", "XL"],
        color: "Gray",
        price: 449,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVMLWHg6oMSPa-HARP1iLZx-Na4qYZaeVXkw&s",
    },
    {
        name: "Oversized Sweatshirt",
        description:
            "Relaxed oversized sweatshirt for a comfy and laid-back vibe.",
        brand: "VelvaShe",
        material: "Velvet",
        size: ["M", "L", "XL"],
        color: "Navy",
        price: 1450,
        category: "WOMEN",
        image: "https://d1ejm5im4bv2vf.cloudfront.net/pub/media/mf_webp/jpg/media/catalog/product/cache/718154c3aff62b1ad64160986aa81112/n/a/navy-women_s-oversized-sweatshirt-front.webp",
    },
    {
        name: "Fairy Wing Dress",
        description:
            "A playful fairy dress with attached wings and sparkly details. Enchanting wear!",
        brand: "StarSprout",
        material: "Rayon",
        size: ["XS", "S", "M"],
        color: "Blue",
        price: 1199,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/51jAuZcd5sL._UF350,350_QL80_.jpg",
    },
    {
        name: "Cargo Shorts",
        description:
            "Durable cargo shorts with plenty of pockets for treasures. Great for outdoor adventures.",
        brand: "WhizKid",
        material: "Tulle",
        size: ["S", "M", "L"],
        color: "Gray",
        price: 1395,
        category: "KIDS",
        image: "https://image.hm.com/assets/hm/17/0a/170a5704ce946d7aad66dc720649a832e4001992.jpg?imwidth=768",
    },
    {
        name: "Cami Top",
        description:
            "Light camisole top with spaghetti straps. A breezy option for hot days or layering.",
        brand: "LilyLine",
        material: "Nylon",
        size: ["XS", "S", "M", "L"],
        color: "Black",
        price: 1249,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/81qW-MmiRLL._UY1100_.jpg",
    },
    {
        name: "Floral Wrap Dress",
        description:
            "A lightweight wrap dress featuring a vibrant floral print. Ideal for brunches, dates, or casual outings.",
        brand: "VivaModa",
        material: "Chiffon",
        size: ["S", "M", "L", "XL"],
        color: "Mint",
        price: 1449,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/81sgG9zQ8gL.jpg",
    },
    {
        name: "Animal Tracks Hoodie",
        description:
            "Hoodie with paw print graphics and animal ears. A hit with young animal lovers.",
        brand: "CozyCritters",
        material: "Knitted Blend",
        size: ["XS", "S", "M"],
        color: "Gray",
        price: 599,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/61XvB7oRpXL._AC_SL1000_.jpg",
        isFeatured: true,
    },
    {
        name: "Everyday Zip Hoodie",
        description:
            "A full-zip hoodie made from a breathable cotton blend with front pockets and adjustable hood. Perfect for layering or light outdoor wear.",
        brand: "TrailGear",
        material: "Rayon",
        size: ["M", "L", "XL", "XXL"],
        color: "Black",
        price: 599,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG2_TVkKUz1CRVWQMhqlOmN2OFQ3NUmMMy-w&s",
    },
    {
        name: "Colorblock Windbreaker",
        description:
            "Lightweight and functional windbreaker jacket with a trendy colorblock design. Ideal for breezy days or light rain while keeping you stylish.",
        brand: "RusticMode",
        material: "Canvas",
        size: ["S", "M", "L", "XL"],
        color: "Silver",
        price: 1395,
        category: "MEN",
        image: "https://tigc.in/cdn/shop/files/compress_1121-wch-04-grey__3.jpg?v=1720766406&width=360",
    },
    {
        name: "Animal Pajama Set",
        description:
            "Soft cotton pajamas featuring cute animal designs. Ideal for a comfy and cozy night’s sleep.",
        brand: "GiggleWear",
        material: "Denim",
        size: ["S", "M", "L", "XL"],
        color: "Peach",
        price: 749,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/51fUvb4a10L._AC_UY1100_.jpg",
    },
    {
        name: "Faux Skirt",
        description: "Bold faux mini skirt for edgy style statements.",
        brand: "ModernGaze",
        material: "Lace",
        size: ["S", "M", "L"],
        color: "Mustard",
        price: 1395,
        category: "WOMEN",
        image: "https://i.pinimg.com/474x/f5/42/1b/f5421b2eeb715a00c4f0fc8b2d19fff2.jpg",
    },
    {
        name: "Ribbed Knit Sweater",
        description:
            "Soft rib-knit sweater with a fitted silhouette. Ideal for layering during cooler days.",
        brand: "StyleMuse",
        material: "Linen",
        size: ["S", "M", "L", "XL"],
        color: "Turquoise",
        price: 1299,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAWZwvCFHIu46dPAXJt825IV8h1l5kKRitw&s",
    },
    {
        name: "Knitted Pullover Sweater",
        description:
            "Classic pullover sweater with ribbed cuffs and hem. Soft knit fabric offers a cozy feel, great for cold days and layering in winter.",
        brand: "SnowCore",
        material: "Polyester",
        size: ["M", "L", "XL"],
        color: "Yellow",
        price: 1249,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqQoYSX7Kt3Yg-P6UzaZq50ipCxWoo8nUaSw&s",
    },
    {
        name: "Casual Linen Shorts",
        description:
            "Comfortable shorts made from a breezy linen-cotton blend. Great for beachwear, travel, or lounging during warm seasons with a light feel.",
        brand: "TrailFlex",
        material: "Fleece",
        size: ["M", "L", "XL"],
        color: "Maroon",
        price: 1199,
        category: "MEN",
        image: "https://i5.walmartimages.com/seo/Plus-Size-Summer-Casual-Solid-Color-Cotton-And-Linen-Shorts-for-Men-Men-s-Five-Minute-Pants-Loose-Retro-Breathable-Men-Shorts-Red_47964a12-2fae-4a81-b0fe-310040a50d24.8ad3fe67066ff712edb466914fe78c2d.jpeg",
    },
    {
        name: "Front Tie Blouse",
        description:
            "Blouse featuring a front knot design. Pairs perfectly with high-waisted bottoms.",
        brand: "AuraVibe",
        material: "Denim",
        size: ["S", "M", "L"],
        color: "Mustard",
        price: 949,
        category: "WOMEN",
        image: "https://i.pinimg.com/736x/cd/d1/ef/cdd1ef674314110a2e4a5e8b49ade29a.jpg",
    },
    {
        name: "Jersey Midi Dress",
        description: "Soft jersey dress with midi length and casual elegance.",
        brand: "GraceNote",
        material: "Satin",
        size: ["M", "L", "XL"],
        color: "Pink",
        price: 949,
        category: "WOMEN",
        image: "https://www.creaturesofhabit.in/cdn/shop/files/SunsetPink_XS_10204001_1_1080x.jpg?v=1719200084",
    },
    {
        name: "Cuffed Chino Pants",
        description:
            "Classic chinos with a modern slim fit and cuffed ankles. Blends style and functionality for both office and casual wear.",
        brand: "RusticMode",
        material: "Cotton",
        size: ["S", "M", "L", "XL"],
        color: "Beige",
        price: 449,
        category: "MEN",
        image: "https://assets.ajio.com/medias/sys_master/root/20240814/5cqp/66bcb77c1d763220fa7af765/-1117Wx1400H-442667219-beige-MODEL.jpg",
    },
    {
        name: "Everyday Crew Socks",
        description:
            "Soft and durable crew socks made for daily use. Moisture-wicking and breathable fabric keeps your feet dry and comfortable all day long.",
        brand: "TrailGear",
        material: "Spandex",
        size: ["M", "L"],
        color: "Red",
        price: 949,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZyT6xJ3SeC3YjzAC3dg_RXlIFA9n_Xh0kGw&s",
    },
    {
        name: "School Uniform Pants",
        description:
            "Simple uniform-style pants with an adjustable waist. Designed for school comfort.",
        brand: "MerryMob",
        material: "Knitted Blend",
        size: ["S", "M", "L", "XL"],
        color: "Orange",
        price: 449,
        category: "KIDS",
        image: "https://imagescdn.peterengland.com/img/app/product/8/891046-10789556.jpg?auto=format&w=390",
    },
    {
        name: "Slim Fit Trousers",
        description:
            "Tailored slim trousers suitable for office or dinner nights. Clean, chic lines with stretch comfort.",
        brand: "VelvaShe",
        material: "Wool",
        size: ["S", "M", "L", "XL"],
        color: "Lilac",
        price: 499,
        category: "WOMEN",
        image: "https://imagescdn.vanheusenindia.com/img/app/product/3/39683704-13929298.jpg?auto=format&w=390",
    },
    {
        name: "Hooded Poncho Towel",
        description:
            "Towel poncho that makes bath time fun and cozy. Comes with animal ear hood designs.",
        brand: "GiggleWear",
        material: "Linen",
        size: ["XS", "S", "M"],
        color: "Yellow",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/612u+eRxiAL.jpg",
    },
    {
        name: "Cowl Neck Sweater",
        description:
            "Soft sweater with draped cowl neckline. Cozy and stylish.",
        brand: "SoftHue",
        material: "Cotton",
        size: ["M", "L", "XL"],
        color: "Lavender",
        price: 1399,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwxNOC6z_-JSQjFA5Bk3949SknIXYq3J47IQ&s",
    },
    {
        name: "Glitter Leggings",
        description:
            "Shimmering leggings perfect for playdates and parties. Soft, stretchable fabric.",
        brand: "GiggleWear",
        material: "Jersey",
        size: ["XS", "S", "M", "L"],
        color: "Purple",
        price: 899,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/71jBs4RKyRL.jpg",
    },
    {
        name: "Basic Tees 3-Pack",
        description:
            "A set of basic crew-neck tees in fun colors. Everyday essentials for kids on the go.",
        brand: "LittleLoop",
        material: "Spandex",
        size: ["S", "M", "L"],
        color: "Turquoise",
        price: 1449,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlwJMRQGybnXxbCv-o4HcRg0nktkrNIq-u-A&s",
    },
    {
        name: "Holiday Sweater",
        description:
            "Festive sweater with bright patterns and holiday vibes. A winter season must-have!",
        brand: "MerryMob",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "Sky Blue",
        price: 549,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlwU0gw_SeEO7kRnVeDcMfdSuPdCRzI81R7Q&s",
    },
    {
        name: "Athletic Shorts",
        description:
            "Lightweight and quick-drying athletic shorts made for workouts and running. Features side pockets and an elastic waistband with drawstring.",
        brand: "DenimWorks",
        material: "Viscose",
        size: ["S", "M", "L"],
        color: "Silver",
        price: 649,
        category: "MEN",
        image: "https://m.media-amazon.com/images/I/71Mygi2VxTL._UY1000_.jpg",
    },
    {
        name: "Peplum Top",
        description:
            "Chic peplum top with a fitted bodice and flared hem. Great for flattering silhouettes.",
        brand: "FemmeFit",
        material: "Georgette",
        size: ["S", "M", "L"],
        color: "Maroon",
        price: 699,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqH4J6D-anU31mEMQEEpMH61Ibd7gblDOqUw&s",
    },
    {
        name: "V-Neck Sweater",
        description:
            "Elegant V-neck sweater that blends warmth and sophistication. Ideal for layering over a shirt in business-casual or smart-casual settings.",
        brand: "ExecutiveLine",
        material: "Viscose",
        size: ["M", "L", "XL"],
        color: "Navy",
        price: 499,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbD7MMnLtECslo08q7LUtmg7Da4HfHGKBjOA&s",
    },
    {
        name: "Checked Casual Shirt",
        description:
            "Button-down checked shirt with a relaxed fit and soft texture. Great for everyday wear and easy to pair with jeans or chinos.",
        brand: "RusticMode",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Teal",
        price: 1450,
        category: "MEN",
        image: "https://imagescdn.pantaloons.com/img/app/product/9/936867-11955957.jpg?auto=format&w=450",
    },
    {
        name: "Classic Buttonless Tee",
        description:
            "A no-fuss round-neck tee without any buttons or graphics. Clean design ideal for those who prefer simple, everyday clothing staples.",
        brand: "RusticMode",
        material: "Canvas",
        size: ["S", "M", "L", "XL"],
        color: "Yellow",
        price: 1449,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMLdogHTPmTrHwkgesC6buO9h2cgZ5kg5_dw&s",
    },
    {
        name: "Herringbone Shirt Jacket",
        description:
            "A stylish shirt jacket with a subtle herringbone texture. Mid-weight, great for transitional weather, and perfect over a tee or henley.",
        brand: "UrbanEdge",
        material: "Viscose",
        size: ["M", "L", "XL"],
        color: "Teal",
        price: 449,
        category: "MEN",
        image: "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/2024/NOVEMBER/29/3KvpXYsE_5cd9e63ac63a4d7995c468066aa137ce.jpg",
    },
    {
        name: "Adventure Jacket",
        description:
            "Lightweight jacket with a fun adventure map print inside. Keeps little explorers warm.",
        brand: "LittleLoop",
        material: "Knitted Blend",
        size: ["S", "M", "L", "XL"],
        color: "Black",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/71t3JS1WxEL._AC_UY1100_.jpg",
    },
    {
        name: "Tunic Dress",
        description:
            "Knee-length tunic dress with a relaxed fit. Ideal for daily comfort and ease.",
        brand: "VivaModa",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Pink",
        price: 799,
        category: "WOMEN",
        image: "https://assets0.mirraw.com/images/12310887/image_zoom.jpeg?1709631121",
    },
    {
        name: "Modern Fit Casual Blazer",
        description:
            "A sharp yet casual blazer that brings a modern edge to semi-formal looks. Lightweight fabric makes it suitable for indoor and seasonal wear.",
        brand: "WoolCraft",
        material: "Canvas",
        size: ["M", "L", "XL"],
        color: "Black",
        price: 949,
        category: "MEN",
        image: "https://imagescdn.louisphilippe.com/img/app/product/9/907509-11192420.jpg?auto=format&w=390",
    },
    {
        name: "Thermal Base Layer Top",
        description:
            "Stay warm in cold weather with this thermal long sleeve top. Soft on the skin and built to retain body heat while allowing breathability.",
        brand: "TrailFlex",
        material: "Denim",
        size: ["M", "L", "XL"],
        color: "Maroon",
        price: 549,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPdXLXyNu5jpKI6u4CAw3GL8KoBaSCDRf9CA&s",
    },
    {
        name: "Hooded Sweatshirt",
        description:
            "A warm fleece-lined hoodie perfect for cooler days. Stylish design with a kangaroo pocket and drawstring hood for added warmth and comfort.",
        brand: "FitZone",
        material: "Fleece",
        size: ["M", "L", "XL", "XXL"],
        color: "Olive",
        price: 699,
        category: "MEN",
        image: "https://www.globalrepublic.in/cdn/shop/products/1_32cb8577-c630-4e43-ac47-8f7f0d35e07a.jpg?v=1648815314",
    },
    {
        name: "Emoji Tee",
        description:
            "Tee with cool emoji prints that kids love. Bright, breathable, and expressive.",
        brand: "CozyCritters",
        material: "Terry",
        size: ["XS", "S", "M", "L"],
        color: "Orange",
        price: 549,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3j0C4F281nvRHI_eBqv9nc_WBMvMSqV6m_Q&s",
    },
    {
        name: "Colorful Swim Trunks",
        description:
            "Quick-drying swim trunks in fun prints. Great for beach days or pool fun.",
        brand: "SoftNest",
        material: "Knitted Blend",
        size: ["XS", "S", "M", "L"],
        color: "Lavender",
        price: 1449,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/618kyGFROBL._UY1000_.jpg",
        isFeatured: true,
    },
    {
        name: "Bright Knit Pullover",
        description:
            "Colorful knit pullover sweater to brighten up cold days. Soft and cozy.",
        brand: "PuddlePals",
        material: "Velour",
        size: ["S", "M", "L"],
        color: "White",
        price: 549,
        category: "KIDS",
        image: "https://5.imimg.com/data5/ECOM/Default/2024/11/466140093/PS/HQ/YS/236083596/1614070265785-500x500.jpg",
    },
    {
        name: "Adventure Print Tee",
        description:
            "Adventure-themed t-shirt with maps, compasses, and tents. Inspires imagination.",
        brand: "LivelyLoom",
        material: "Acrylic",
        size: ["S", "M", "L"],
        color: "Blue",
        price: 599,
        category: "KIDS",
        image: "https://images.meesho.com/images/products/433468861/gxkes_512.webp",
    },
    {
        name: "Faded Denim Shirt",
        description:
            "Stylish faded denim shirt with snap buttons and chest pockets. A rugged piece that works well open over a t-shirt or buttoned up.",
        brand: "StreetPulse",
        material: "Spandex",
        size: ["M", "L", "XL"],
        color: "Black",
        price: 699,
        category: "MEN",
        image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2130555/2017/11/4/11509788180226-Roadster-Men-Black-Slim-Fit-Faded-Casual-Shirt-151509788180000-1.jpg",
    },
    {
        name: "Party Dress",
        description:
            "Elegant dress with lace trim and soft tulle skirt. Designed for birthdays and special days.",
        brand: "MiniMode",
        material: "Velour",
        size: ["XS", "S", "M"],
        color: "Navy",
        price: 699,
        category: "KIDS",
        image: "https://www.houseofclaire.com/cdn/shop/products/Navy_OffGown2.jpg?v=1676227933&width=1445",
    },
    {
        name: "Knitted Winter Beanie",
        description:
            "A stylish ribbed beanie perfect for cold weather. Offers warmth and snug fit, keeping you comfortable and cozy during the winter months.",
        brand: "RusticMode",
        material: "Silk",
        size: ["M", "L"],
        color: "Gray",
        price: 699,
        category: "MEN",
        image: "https://i.etsystatic.com/10866204/r/il/7c9c8a/4118668590/il_570xN.4118668590_5n2n.jpg",
    },
    {
        name: "Casual Polo Shirt",
        description:
            "A sleek and breathable polo shirt designed for comfort during casual outings or semi-formal events. Perfect for pairing with jeans or chinos.",
        brand: "RainGuard",
        material: "Nylon",
        size: ["M", "L", "XL", "XXL"],
        color: "Red",
        price: 499,
        category: "MEN",
        image: "https://www.cotstyle.com/cdn/shop/files/PL01_387091_1.jpg?v=1682765323",
    },
    {
        name: "Black Jogger Pants",
        description:
            "Slim-fit joggers designed for everyday wear and workouts. Stretchable waistband, side pockets, and soft fabric make them a must-have for comfort seekers.",
        brand: "RainGuard",
        material: "Silk",
        size: ["S", "M", "L", "XL"],
        color: "Orange",
        price: 1499,
        category: "MEN",
        image: "https://5.imimg.com/data5/SELLER/Default/2020/11/ZZ/WC/PB/26172866/71b34bloldl-ul1500-.jpg",
    },
    {
        name: "Ruched Bodycon Dress",
        description: "Bodycon dress with ruched sides for a slimming effect.",
        brand: "VelvaShe",
        material: "Lace",
        size: ["S", "M", "L"],
        color: "Charcoal",
        price: 549,
        category: "WOMEN",
        image: "https://cdn-img.prettylittlething.com/6/a/9/6/6a96303177980679ca0aed24b84855744cb982f9_CNM3156_1_charcoal_stretch_woven_ruched_bodycon_dress.jpg",
    },
    {
        name: "Culotte Pants",
        description:
            "High-waisted culottes with cropped wide legs. Smart-casual essential.",
        brand: "ChicLayer",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Cream",
        price: 1499,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkh_sE1yHmdm8Hx2U152J28ZyI7xU5JoPvmg&s",
    },
    {
        name: "Classic V-Neck Tee",
        description:
            "Simple and soft V-neck t-shirt for daily wear. Breathable cotton fabric and a slim fit create a flattering and comfortable silhouette.",
        brand: "StepEase",
        material: "Linen",
        size: ["S", "M", "L", "XL"],
        color: "Green",
        price: 699,
        category: "MEN",
        image: "https://interwove.in/cdn/shop/products/bamboo-classic-v-neck-t-shirt-898007.jpg?v=1746968379&width=375",
    },
    {
        name: "Oversized Hoodie",
        description:
            "Stay cozy in this oversized hoodie with a relaxed fit and kangaroo pocket. Ideal for lounging or streetwear-inspired outfits.",
        brand: "BaseLayer",
        material: "Polyester",
        size: ["M", "L", "XL", "XXL"],
        color: "Turquoise",
        price: 599,
        category: "MEN",
        image: "https://assets.ajio.com/medias/sys_master/root/20250320/mKGN/67db9f6d55340d4b4f7a6e56/-473Wx593H-700420451-turquoise-MODEL4.jpg",
    },
    {
        name: "Classic Henley Shirt",
        description:
            "A comfortable and versatile long-sleeve henley shirt made from breathable cotton. Ideal for layering or wearing on its own during casual days.",
        brand: "StepEase",
        material: "Canvas",
        size: ["M", "L", "XL"],
        color: "Brown",
        price: 649,
        category: "MEN",
        image: "https://m.media-amazon.com/images/I/61UPu+nqtZL._UY1100_.jpg",
    },
    {
        name: "Graphic Overcoat",
        description:
            "A warm overcoat with colorful cartoon graphics. Winter wear that kids love to wear.",
        brand: "LittleLoop",
        material: "Spandex",
        size: ["S", "M", "L", "XL"],
        color: "Yellow",
        price: 499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/51uP01voskL._AC_UY1100_.jpg",
    },
    {
        name: "Slim Fit Jeans",
        description:
            "These slim-fit jeans offer a modern, tailored look with a comfortable stretch. Ideal for daily wear or dressing up for a night out.",
        brand: "EveryWear",
        material: "Rayon",
        size: ["S", "M", "L", "XL"],
        color: "Beige",
        price: 1299,
        category: "MEN",
        image: "https://spykar.com/cdn/shop/products/MDSKN1BD045Beige_1.jpg?v=1737640045",
    },
    {
        name: "Twill Button Shirt",
        description:
            "This classic twill shirt offers a clean, polished look for both work and casual wear. Features a soft brushed texture and durable fabric.",
        brand: "LayerUp",
        material: "Suede",
        size: ["M", "L", "XL", "XXL"],
        color: "Coral",
        price: 699,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoZXK3GiMEzwo-WwqFof81UJlgflrHmg5k4g&s",
    },
    {
        name: "Striped Casual Tee",
        description:
            "Casual short sleeve tee with horizontal stripes and a comfortable relaxed fit. Great for beach days or casual weekends with friends.",
        brand: "ExecutiveLine",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Gray",
        price: 1249,
        category: "MEN",
        image: "https://i.pinimg.com/736x/d6/ee/07/d6ee073a6deb9e12cd172a6a1b299aa6.jpg",
    },
    {
        name: "Summer Overalls",
        description:
            "Light cotton overalls perfect for sunny days. Features adjustable shoulder straps.",
        brand: "KiddoStyle",
        material: "Linen",
        size: ["S", "M", "L"],
        color: "Black",
        price: 449,
        category: "KIDS",
        image: "https://www.dungarees-online.com/cdn/shop/products/matthew-slim-fit-dungaree-black.jpg?v=1608748938",
    },
    {
        name: "Denim Overalls",
        description:
            "Stylish denim overalls with adjustable straps and pocket front.",
        brand: "UrbanBelle",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "Rose",
        price: 1099,
        category: "WOMEN",
        image: "https://i.pinimg.com/736x/9a/7f/cc/9a7fcc5c7b4b2f531406f55b1ed7bba8.jpg",
    },
    {
        name: "Striped Polo Shirt",
        description:
            "Smart-casual striped polo shirt that’s both comfortable and stylish.",
        brand: "CubCove",
        material: "Jersey",
        size: ["XS", "S", "M", "L"],
        color: "Sky Blue",
        price: 1199,
        category: "KIDS",
        image: "https://tiimg.tistatic.com/fp/1/008/242/boys-striped-polo-neck-short-sleeve-t-shirt-364.jpg",
    },
    {
        name: "Plaid Button-Up Shirt",
        description:
            "Classic plaid shirt great for school or casual events. Made with soft, brushed fabric.",
        brand: "LivelyLoom",
        material: "Jersey",
        size: ["S", "M", "L", "XL"],
        color: "Red",
        price: 1450,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/71OGdPtNIcL._UY1100_.jpg",
    },
    {
        name: "Relaxed Fit Henley",
        description:
            "Casual long-sleeve henley with button collar and relaxed silhouette. Combines classic design with soft fabric for all-day comfort.",
        brand: "DenimWorks",
        material: "Viscose",
        size: ["S", "M", "L", "XL"],
        color: "Olive",
        price: 799,
        category: "MEN",
        image: "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/2170596/2018/7/9/f908dffb-1725-4e09-9c18-5c38d5075d2c1531130515653-Roadster-Men-Olive-Green-Solid-Henley-Neck-T-shirt-417153113-1.jpg",
    },
    {
        name: "Galaxy Print Pajamas",
        description:
            "Cosmic print pajamas for dreamers and stargazers. Super comfy fabric for deep sleep.",
        brand: "PlayPatch",
        material: "Linen",
        size: ["S", "M", "L"],
        color: "Lavender",
        price: 899,
        category: "KIDS",
        image: "https://i5.walmartimages.com/seo/Renewold-Comfortable-Kid-Pjs-Boy-Girls-Galaxy-Pajamas-Top-Pants-Birthday-Gifts-Sot-Long-Sleeve-Nightwear-Relaxed-Indoor-Outfits-Matching-Set-2-Size-7_ba6c8732-7ae7-46d8-9098-a851708ff9e9.2864a584489c42f6911db0d4fb3ee52a.jpeg",
    },
    {
        name: "Safari Explorer Shirt",
        description:
            "Button-up shirt with playful safari animal prints. Lightweight and perfect for curious little adventurers.",
        brand: "WhizKid",
        material: "Spandex",
        size: ["S", "M", "L", "XL"],
        color: "Blue",
        price: 899,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_iTf15V2gLun9NvTyfjqB8pyUgz94qG0TQ&s",
    },
    {
        name: "Denim Jacket",
        description:
            "Classic denim jacket with a slightly cropped cut and distressed finish. A timeless wardrobe staple.",
        brand: "AuraVibe",
        material: "Spandex",
        size: ["S", "M", "L", "XL"],
        color: "Coral",
        price: 549,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/71hRPhHojjL._AC_UY1100_.jpg",
    },
    {
        name: "Basic Round Neck Tee",
        description:
            "Essential round neck t-shirt with a clean look and relaxed fit. Great for everyday wear or as a base layer under jackets and shirts.",
        brand: "CoreStyle",
        material: "Rayon",
        size: ["S", "M", "L", "XL"],
        color: "Olive",
        price: 1450,
        category: "MEN",
        image: "https://static.cilory.com/724652-thickbox_default/grunt-light-olive-basic-round-neck-t-shirt.jpg.webp",
    },
    {
        name: "Wrap Blouse",
        description:
            "Wrap-style blouse that ties at the waist for a flattering look.",
        brand: "GraceNote",
        material: "Lace",
        size: ["S", "M", "L"],
        color: "Sky Blue",
        price: 749,
        category: "WOMEN",
        image: "https://babli.in/cdn/shop/products/Sky-Blue-Wrap-Top-5.jpg?v=1701254598",
    },
    {
        name: "Empire Waist Top",
        description:
            "Empire waistline top that enhances shape and provides comfort.",
        brand: "LuxeCharm",
        material: "Cotton",
        size: ["S", "M", "L"],
        color: "White",
        price: 1099,
        category: "WOMEN",
        image: "https://tigc.in/cdn/shop/files/compress_0523-fhaatop-22-white__3.jpg?v=1720731809",
    },
    {
        name: "Ruffle Hem Skirt",
        description:
            "Flirty mini skirt with a ruffled hemline. Youthful and playful.",
        brand: "GlowThread",
        material: "Rayon",
        size: ["XS", "S", "M"],
        color: "Rose",
        price: 449,
        category: "WOMEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLvFV8ld1tlsgcxDTZ58oGgaIRt9Int-_DIg&s",
    },
    {
        name: "Pleated Midi Skirt",
        description:
            "Elegant midi skirt with fine pleats and a flowy silhouette. Pairs beautifully with blouses or tucked-in tees.",
        brand: "SoftHue",
        material: "Lace",
        size: ["S", "M", "L", "XL"],
        color: "Turquoise",
        price: 1099,
        category: "WOMEN",
        image: "https://i.pinimg.com/736x/07/34/fa/0734fa547f9b5fb000100468c667f70c.jpg",
        isFeatured: true,
    },
    {
        name: "Fun Socks Pack",
        description:
            "Pack of playful printed socks to keep little feet warm and colorful.",
        brand: "CozyCritters",
        material: "Cotton",
        size: ["XS", "S", "M"],
        color: "Maroon",
        price: 1499,
        category: "KIDS",
        image: "https://m.media-amazon.com/images/I/81W4uDTvNfL._AC_UY1100_.jpg",
    },
    {
        name: "Puffer Vest",
        description:
            "A puffy sleeveless vest for layering during colder seasons. Lightweight yet warm.",
        brand: "LittleLoop",
        material: "Spandex",
        size: ["S", "M", "L"],
        color: "Orange",
        price: 1299,
        category: "KIDS",
        image: "https://i1.adis.ws/i/janieandjack/101383001_alt_JJ/color?$PDP_main$",
    },
    {
        name: "Boho Maxi Dress",
        description:
            "Bohemian-style maxi dress with tiered layers and a tie waist. Great for vacations or beach strolls.",
        brand: "StyleMuse",
        material: "Satin",
        size: ["M", "L", "XL"],
        color: "Beige",
        price: 749,
        category: "WOMEN",
        image: "https://i.pinimg.com/474x/1a/d7/5e/1ad75ead34cf7a3c8b4e1df664eb77cb.jpg",
    },
    {
        name: "Off-Shoulder Top",
        description:
            "Trendy off-shoulder blouse with ruffle details. Perfect for summer dates or girls' night out.",
        brand: "AuraVibe",
        material: "Rayon",
        size: ["S", "M", "L"],
        color: "Lavender",
        price: 749,
        category: "WOMEN",
        image: "https://assets.ajio.com/medias/sys_master/root/20240717/3JoF/6696d8a71d763220faca3295/-473Wx593H-463304672-purple-MODEL.jpg",
    },
    {
        name: "Ruffled Sleeve Tee",
        description: "Everyday t-shirt with feminine ruffle sleeve detail.",
        brand: "AuraVibe",
        material: "Acrylic",
        size: ["S", "M", "L", "XL"],
        color: "Coral",
        price: 1450,
        category: "WOMEN",
        image: "https://assets.ajio.com/medias/sys_master/root/20230208/7VXa/63e34189aeb26924e35e54bb/-473Wx593H-443002579-coral-MODEL.jpg",
    },
    {
        name: "Fit & Flare Dress",
        description:
            "A flattering fit-and-flare dress with a cinched waist. Works great for both formal and fun events.",
        brand: "SheNova",
        material: "Nylon",
        size: ["S", "M", "L"],
        color: "Navy",
        price: 649,
        category: "WOMEN",
        image: "https://oyela.in/cdn/shop/files/4_1f98d85b-ba0b-4047-b77e-9ce56fc15f20-552413.jpg?v=1746600332",
    },
    {
        name: "Balloon Sleeve Top",
        description:
            "Elegant top with dramatic balloon sleeves and soft fabric feel.",
        brand: "VivaModa",
        material: "Nylon",
        size: ["S", "M", "L"],
        color: "Lavender",
        price: 1299,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/430166966/mhr9w_512.webp",
    },
    {
        name: "Crochet Crop Top",
        description:
            "Handmade-looking crochet crop top for beachwear or summer vibes.",
        brand: "TrendMuse",
        material: "Lace",
        size: ["XS", "S", "M"],
        color: "White",
        price: 1450,
        category: "WOMEN",
        image: "https://images.meesho.com/images/products/280085728/3lesr_512.webp",
    },
    {
        name: "Heathered Crew Tee",
        description:
            "Soft heathered t-shirt designed for comfort and style. Lightweight fabric and subtle texture make it a go-to piece for daily wear.",
        brand: "RainGuard",
        material: "Silk",
        size: ["S", "M", "L", "XL"],
        color: "Pink",
        price: 1199,
        category: "MEN",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzdzyBMC4yD9eDgpR7ZxN7OUJ5Lm7CWgmorQ&s",
    },
    {
        name: "Graphic T-Shirt",
        description: "Statement graphic tee for a casual and confident look.",
        brand: "UrbanBelle",
        material: "Wool",
        size: ["S", "M", "L", "XL"],
        color: "Olive",
        price: 1349,
        category: "WOMEN",
        image: "https://m.media-amazon.com/images/I/91hoA72bHbL._UY1100_.jpg",
        isFeatured: true,
    },
    {
        name: "Softshell Vest",
        description:
            "A windproof softshell vest ideal for layering in cool weather. Offers core warmth without adding bulk, suitable for hiking and travel.",
        brand: "SnowCore",
        material: "Canvas",
        size: ["M", "L", "XL"],
        color: "Brown",
        price: 549,
        category: "MEN",
        image: "https://www.ariat.com/dw/image/v2/AAML_PRD/on/demandware.static/-/Sites-ARIAT/default/dwa50fc040/images/warm/10052596_front_warm.jpg?sw=800&sh=800",
    },
    {
        name: "Denim Skirt",
        description:
            "Classic denim skirt with stretch waist and contrast stitching. Cute and versatile.",
        brand: "GiggleWear",
        material: "Terry",
        size: ["S", "M", "L"],
        color: "Lavender",
        price: 949,
        category: "KIDS",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeT_S-RqXLuZHPKKof3nzZjdxmBvJurSZA6A&s",
    },
    {
        name: "Chiffon Tunic",
        description:
            "Flowy chiffon tunic with flared sleeves. Effortlessly blends elegance with comfort.",
        brand: "ModernGaze",
        material: "Acrylic",
        size: ["M", "L", "XL"],
        color: "Wine",
        price: 1099,
        category: "WOMEN",
        image: "https://tanhai.in/cdn/shop/files/121_a86603bb-3a6b-42b3-b3d0-b4674cd0cc53.jpg?v=1707972910",
    },
];
